### ISSUE TITLE
Feature request: Resizable selection boxes.

### ISSUE THREAD

**Issue by ryanbrainard** [forceworkbench/forceworkbench#525]
_Original author: Ironsh...@gmail.com (August 26, 2011 07:12:34)_

<b>1. Summary of the feature request:</b>
1. Log into workbench
2. Choose SOQL query
3. Look at the screen realestate for the field and object boxes

What is the expected output? What do you see instead?
They are formtted to be very small in size. It would be better if this could be resizable or at least longer, to incorporate very long field names

On what operating system and browser?
WIndows 7 64bit, Firefox 6

<b>2. Typical scenerio where this feature would be used:</b>
Any time that a field name is very long, or there are many fields. It's easier to see more than six at once.

<b>3. Reason current features do not meet needs:</b>
modern screens have higher resolutions, and field names aren't always short. 

<b>4. How soon would you like to see this feature implemented?</b>
As soon as is reasonably possible.

_Original issue: http://code.google.com/p/forceworkbench/issues/detail?id=525_

**Comment by boparaiaman** [comment]
![image](https://user-images.githubusercontent.com/45497131/50019388-748c4480-ffa0-11e8-8196-9e51946993a1.png)

**Comment by mikeflemingcfs** [comment]
I concur.  I think what @ryanbrainard meant was for the Fields window to be wider (dynamic to the maximum number of characters allowed in a Field name?), or at least so that the window can be manually expanded.
