### ISSUE TITLE
oAuth problems with Salesforce sandboxes since Spring 15 preview began

### ISSUE THREAD

**Issue by diligent176** [forceworkbench/forceworkbench#650]
Is anyone else experiencing "login looping" with workbench and SFDC sandboxes?
Ever since Jan 8th (roughly when Spring 15 preview started) the oAuth behavior in Workbench is failing frequently. 
(sandboxes only, production is fine)

**Steps to reproduce:**
1) Login to my sandbox as a System Admin
2) Open a new tab, navigate to https://workbench.developerforce.com
3) Select "Sandbox" and agree to Terms of Service
4) Click "Login with Salesforce"

**Result:**
I arrive at SFDC login page again.  Upon entering valid credentials, I am redirected to SFDC home page, not into workbench.

**Expected Result:**
Arrive at workbench screen.

Sometimes this "login loop" repeats 2 to 6 times before workbench finally opens.

I'm positive this is an SFDC "login host" issue because - identical behavior can be seen with "PermComparator" app.
The same oAuth failure occurs: https://perm-comparator.herokuapp.com

I've opened a premier case with SFDC, but they will not support anything to do with 3rd party apps.
Even though I've 80% proven it's a problem at their side - I'm not getting any traction with their support team.

Any insight or assistance would be much appreciated!!

Jason

**Comment by diligent176** [comment]
It's looking like this issue is only happening for SFDC sandboxes created specifically from my company's production org.  

I created a 30-day trial org "for advanced admins", and it came with 2 sandbox licenses.
Those sandboxes (on CS18) do not reproduce the issue, but my company's sandboxes (also on CS18 and on other hosts) easily reproduce the issue.

**Comment by ptolemyrulz** [comment]
I am also experiencing this issue with my client's org.  They are using a custom domain and I can't get into Workbench, CS10...

**Comment by diligent176** [comment]
Here's a workaround I've found (albeit - painful).
Assuming you're already logged into SFDC in Chrome for example...
Open a new Incognito window and go directly to workbench.   Select sandbox, then login as usual to SFDC.  Workbench should open.

I've become accustomed to this now - I can only use workbench following the above procedure.  (sigh)..

**Comment by ptolemyrulz** [comment]
Hmm...that doesn't work for me.  My org is https://clientname--environment.cs10.my.salesforce.com/ and the incognito window still isn't allowing me into the workbench, it keeps re-directing me into the org.  Do you think it has to do with the fact that I have cs10 in the url or something?

**Comment by diligent176** [comment]
Hmm, odd - which browser out of curiosity?  (I've tried them all).
How about this variation on the test...
- Close all browser instances.
- Launch a fresh browser session to https://workbench.developerforce.com
- Select sandbox and login to your destination sandbox
- Workbench should load

Our domain setup is the same.   i.e.
https://clientdomain--sandboxname.cs10.my.salesforce.com

I had a lengthy ticket open with SFDC on this issue because I was positive it began right at the start of Spring 15 preview window.  During troubleshooting we found that by disabling the domains feature it started working.  Only SFDC can disable it for you.

**Comment by sanchayeetaSen** [comment]
Hi All

Even i am facing the same issue.. I am usiing Chrome browser. My Org is  https://clientname--environment.cs14.my.salesforce.com/. Whenever i am trying to open The workbench it redirects me to Login page which in turn opens up the Sandbox homepage instead of Workbench tool. 

San

**Comment by KevinBR72** [comment]
I am experiencing this as well in my org sandbox.

Am using the latest version of chrome.
SF Domain is on CS21.

**Comment by diligent176** [comment]
Great to hear I'm not the only one experiencing it - I thought I was alone :-)
I spent a long time with Salesforce Tier 2 & 3 support (almost two months) and several support cases, but they would not look into the issue purely based on the fact that a 3rd party app is involved.  

I then demonstrated a different third party app (PermComparator) which exhibits the identical behavior.

The only way they (SF) might help support this issue is as a development issue.  i.e. Some developer who has the source code for a third party app (like workbench or perm comparator) who understands the oAuth workflow and how it's failing in this scenario.  

I'm 99% sure the failure is at SFDC end of things, but I am not fluent enough in PHP to debug SFDC workbench code at this level.

**Comment by KevinBR72** [comment]
I found a workaround that worked for me:

a) For posterity, I cleared all of browser (chrome) settings (cache/cookies,etc.) earlier 
b) All browser sessions shutdown and restarted
c) Using icognito mode, launched developer workbench site (selecting sandbox, api 32)
d) Entered full credentials
e) *Before* submitting, I changed "test.salesforce.com" in the url to my org domain
 (ie, OrgName--SandBoxNameuat.cs21.my.salesforce.com) - this was actually suggested to me by Puneet @ SFDC
f) Workbench came up as expected
g) Closed incognito session
h) Opened new browser session to UAT instance (non-incognito mode)
i) Authenticated as normal; launched workbench site
j) A user username page displayed; clicked active/desired user name
k) Workbench came up as expected

**Comment by diligent176** [comment]
Not sure if I follow step e).
Changing the URL in the address bar before submitting the login form will not change where the form is submitted to (unless you also hit ENTER in the URL bar on step e)?

I've found that step not to be necessary.  Bottom line for me is:
- if the browser already has an authenticated SFDC session, cannot get into workbench
- if the browser has no session with SFDC, workbench login succeeds

The identical behavior can be observed with this application as well.
https://perm-comparator.herokuapp.com/
