### ISSUE TITLE
UNKNOWN ERROR: Bad Request when connecting to some sandboxes

### ISSUE THREAD

**Issue by cramoisan** [forceworkbench/forceworkbench#653]
We are getting the following error when trying to connect to some of our newest sandboxes using Workbench 29.0.8: UNKNOWN ERROR: Bad Request. 

It works fine with our older sandboxes.
And it also works fine when reverting to Workbench 29.0.1.

We have tried using API 29 or 32 with the same results.

We use a corporate proxy.
All our sandboxes are on Spring 15.

**Comment by ryanbrainard** [comment]
what request are you making?

**Comment by cramoisan** [comment]
We are simply trying to log in.
We can see a successful connection in the server logs with the Partner API, but I think we get the error when it reuses the session Id to connect to the Metadata or Tooling API.
Is there any way to get some logs on the php server side (we have the workbench deployed on a local wamp server)?

**Comment by ryanbrainard** [comment]
By default Workbench logs to syslog. If you want it to log to a file, add this to `workbench/config/overrides.php`:

    $config["logHandler"]["default"] = "file";

**Comment by cramoisan** [comment]
Here is the event in syslog:
E at=ERROR method=POST path=/workbench-29.0.8/login.php origin=127.0.0.1 v=29.0.8 sfdc=REDACTED.cs17.my.salesforce.com org= user= measure.exception=1 0:Bad Request #0 [internal function]: SoapClient->__doRequest('<?xml version="...', 'https://REDACTED...', '', 1, 0) #1 C:\wamp\www\workbench-29.0.8\soapclient\SforceBaseClient.php(881): SoapClient->__call('getUserInfo', Array) #2 C:\wamp\www\workbench-29.0.8\soapclient\SforceBaseClient.php(881): SoapClient->getUserInfo() #3 C:\wamp\www\workbench-29.0.8\context\UserInfoProvider.php(11): SforceBaseClient->getUserInfo() #4 C:\wamp\www\workbench-29.0.8\context\CacheableValueProvider.php(18): UserInfoProvider->load(NULL) #5 C:\wamp\www\workbench-29.0.8\context\WorkbenchContext.php(231): CacheableValueProvider->get(NULL) #6 C:\wamp\www\workbench-29.0.8\context\WorkbenchContext.php(286): WorkbenchContext->getCacheableValue('USER_INFO') #7 C:\wamp\www\workbench-29.0.8\controllers\LoginController.php(295): WorkbenchContext->getUserInfo() #8 C:\wamp\www\workbench-29.0.8\controllers\LoginController.php(140): LoginController->processLogin('REDACTED', 'REDACTED', 'https://test.sa...', NULL, 'select.php') #9 C:\wamp\www\workbench-29.0.8\login.php(14): LoginController->processRequest() #10 {main}
