### ISSUE TITLE
How to set Batch Size in Workbench

### ISSUE THREAD

**Issue by Abhipsa86** [forceworkbench/forceworkbench#660]
Please help us to set batch size during insert operation.Didn't get any option in Settings
![image](https://cloud.githubusercontent.com/assets/13656757/9081335/1a56153e-3b79-11e5-9ddf-25254ebdf7cf.png)

**Comment by orymeyer** [comment]
@Abhipsa86 , You configure the batch size from the Settings menu, if you deploy your own instance of workbench. This option is not available in the instance hosted on developerforce.com

**Comment by chiragmehta84** [comment]
Oh dear, I too was looking for same since ages. Seems I will have to deploy my own instance and use it. Its must have setting.
