### ISSUE TITLE
Workbench access via Salesforce Subscribers ORG is not working

### ISSUE THREAD

**Issue by pjhaxactly** [forceworkbench/forceworkbench#667]
Workbench is not accessible via Subscribers ORG in salesforce. It throws insufficient Privilege error. 
I have been provided Sys Admin access with API enabled and workbench checked in the profile settings.

**Comment by gs-ryaddanapalli** [comment]
Specifically after Salesforce winter16

**Comment by pjhaxactly** [comment]
correct... anyone else facing this issue?? I bet there are.

*Regards, *
*Pranay*

On Mon, Nov 2, 2015 at 5:51 PM, gs-ryaddanapalli <notifications@github.com>
wrote:

> Specifically after Salesforce winter16
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ryanbrainard/forceworkbench/issues/667#issuecomment-153001613>
> .
>

-- 


[image: What's New with Xactly] <http://www.xactlycorp.com/email-click/>

<https://www.nyse.com/quote/XNYS:XTLY>  [image: LinkedIn] 
<https://www.linkedin.com/company/xactly-corporation>  [image: Twitter] 
<https://twitter.com/Xactly>  [image: Facebook] 
<https://www.facebook.com/XactlyCorp>  [image: YouTube] 
<http://www.youtube.com/xactlycorporation>

**Comment by gs-ryaddanapalli** [comment]
Everyone in my Org are experiencing this. I created a support ticket with SFDC but did not get any positive response.

**Comment by pjhaxactly** [comment]
Yes they sf said its a 3rd party tool and they don't support and hence this forum. But we are only discussing the problem, no solution in sight.

**Comment by adairace7** [comment]
Yes I am seeing this issue as well when trying to access workbench via LMA/Subscribers.   I'm unable to make any calls out to connected Apps after Winter 16 release.

**Comment by pjhaxactly** [comment]
is anyone from workbench looking into this?? I have got an ongoing ticket with sf.

**Comment by john-brock** [comment]
@gs-ryaddanapalli can you send me the support ticket info? I have also posted this issue to a few internal Salesforce teams requesting more info and will post back if I receive any updates.

**Comment by adairace7** [comment]
@john-brock Case number is 12694540

**Comment by gs-ryaddanapalli** [comment]
12694540

**Comment by john-brock** [comment]
Thanks @adairace7 and @gs-ryaddanapalli -- I have a request out for more information and will let you know as soon as I hear something. 
But, while we are waiting, it would help to raise another support case that isn't related to Workbench since it isn't a supported tool. Could you please log another case about the underlying root cause of loosing API access via subscriber orgs and being unable to make any calls out to connected Apps after Winter 16 release.

**Comment by pjhaxactly** [comment]
I raised this generic ticket for connected apps and sf is going to work on
it with me.
Case #12725258
​. SF support has asked me for a ORG access and are still working on it.

*Regards, *
*Pranay*

On Wed, Nov 4, 2015 at 11:17 PM, John Brock <notifications@github.com>
wrote:

> Thanks @adairace7 <https://github.com/adairace7> and @gs-ryaddanapalli
> <https://github.com/gs-ryaddanapalli> -- I have a request out for more
> information and will let you know as soon as I hear something.
> But, while we are waiting, it would help to raise another support case
> that isn't related to Workbench since it isn't a supported tool. Could you
> please log another case about the underlying root cause of loosing API
> access via subscriber orgs and being unable to make any calls out to
> connected Apps after Winter 16 release.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ryanbrainard/forceworkbench/issues/667#issuecomment-153806573>
> .
>

-- 


[image: What's New with Xactly] <http://www.xactlycorp.com/email-click/>

<https://www.nyse.com/quote/XNYS:XTLY>  [image: LinkedIn] 
<https://www.linkedin.com/company/xactly-corporation>  [image: Twitter] 
<https://twitter.com/Xactly>  [image: Facebook] 
<https://www.facebook.com/XactlyCorp>  [image: YouTube] 
<http://www.youtube.com/xactlycorporation>

**Comment by pjhaxactly** [comment]
I have provided salesforce with a login access to one of our test org which is accessible via subscribers org. Salesforce says they haven't heard about such issues. I am just astonished at how and why didn't hear about this.

**Comment by pjhaxactly** [comment]
Haaaaahhhhh!!!!! Got the most ugly solution to enable/disable security feature of salesforce. I was in touch with Brandon (at sf) who informed me that this is security feature of salesforce. They don't provide us connected app access if it is a logged-in-user. This is the reply from Brandon, 

My name is Brandon with the Salesforce Security Team. I am reaching out to assist you with case 12790681 regarding enabling "Allow OAuth Access when logged in as another user".

In order to proceed with enabling this feature, we require a letter signed by the org's System Administrator on company letterhead. 

The letter must contain the following:
1. Organization ID
2. Acknowledgment of the security implications of this change
3. What % of your users are affected? 
4. Does this affect data integrity? 
5. Do you have a viable workaround? 
6. Does this affect critical application functionality? 
7. What business functionality are you unable to perform?, with an example. 
8. Time frame of change requested? Ex. 30 days / indefinitely

Once the letter is received (via email or attached to the support case), I will proceed with this change.

**Comment by pjhaxactly** [comment]
Need a better solution than this for sure....
