### ISSUE TITLE
SOQL Query - Bulk CSV Option Returns Empty File

### ISSUE THREAD

**Issue by tompatros** [forceworkbench/forceworkbench#670]
The Bulk CSV export option in the SOQL Query feature started returning empty export files about a week ago. Query results that definitely have records in them do not output to the CSV export. It appears to work (the download page shows the # of records processed) but export file only contains the column names.

**Comment by ryanbrainard** [comment]
Are you noticing this on a particular API version or everywhere? (Sorry for the delay in responding)

**Comment by tompatros** [comment]
I've been using the default v34 and also tried v35

On Fri, Dec 18, 2015 at 1:31 PM, Ryan Brainard <notifications@github.com>
wrote:

> Are you noticing this on a particular API version or everywhere? (Sorry
> for the delay in responding)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ryanbrainard/forceworkbench/issues/670#issuecomment-165864475>
> .
>



-- 
Tom Patros
Managing Partner
Red Argyle

www.redargyle.com
585 412 2153 x1102
