### ISSUE TITLE
Metadata Retrieve() executes, but zip file not downloadable 

### ISSUE THREAD

**Issue by dbenn8** [forceworkbench/forceworkbench#672]
Hi all,

Retrieve() command is received by server, and asynch auto refreshes seem to work correctly.  Link to Download zip file containing retrieved components is displayed, however, clicking the link throws the following error (and file cannot be downloaded):

> No zip file found for async process id '09S1a000001wcK4EAI'. Note, retrieve results are deleted after first download or navigating away from this page.

This is making the retrieve() command completely unusable as you can imagine.  I'm connecting with version 34.0 of the metadata API.

I've tried turning off the 'automatic refresh of Asynch' in the 'settings' section of workbench as a possible work around (in case the page was being refreshed too many times by that code, where refresh was considered a navigation away), but this didn't help.  If I did a manual refresh a few minutes after submitted to the server, it showed the download link and threw the same error.

Also worth noting that I have also tried API versions 35.0 and 30.0 to see if that would help.

**Comment by datapharmer** [comment]
I'm experiencing the same issue.
