### ISSUE TITLE
Slow response times reported from multiple users

### ISSUE THREAD

**Issue by smayAFG** [forceworkbench/forceworkbench#733]
We seem to be experiencing extremely slow response times from the site.  Specifically trying to execute Rest Explorer requests.  We are still waiting for responses as I'm writing this issue.

**Comment by gibbygano** [comment]
I'd like to second this issue. Very long response times that come back with: 
![image](https://user-images.githubusercontent.com/9158457/31564630-a206a10e-b031-11e7-965c-3599e8aba807.png)
