### ISSUE TITLE
instructions for Upgrading in Heroku

### ISSUE THREAD

**Issue by mkbarcham** [forceworkbench/forceworkbench#742]
There is a simple method for deploying Workbench to Heroku, but absolutely no instruction on how to update it.  The Wiki seems to assume you have deployed to your own web server, but the detail for Heroku deployments is non-existent.  Can you offer any suggestions (short of dropping the app and starting again from scratch)?

**Comment by ryanbrainard** [comment]
Unfortunately, it doesn't look like you can do it from the Dashboard because the code is in a repo you don't own, but this *should* work from the command line:

```sh
export APP_NAME=your-heroku-app-name-here
heroku git:clone -a $APP_NAME
cd $APP_NAME
heroku remote add origin https://github.com/ryanbrainard/forceworkbench.git
git pull origin
git push heroku master
```

...and then on subsequent upgrades, you can just do:

```sh
export APP_NAME=your-heroku-app-name-here
cd $APP_NAME
git pull origin
git push heroku master
```
