### ISSUE TITLE
Login Error: Salesforce Session Invalid or Expired

### ISSUE THREAD

**Issue by aesalpas** [forceworkbench/forceworkbench#744]
I am attempting to login to Workbench but keep getting logged out with the error "An error has occurred and you have been logged out: Your Salesforce session is invalid or has expired. Please login again."
I have cleared my cache/history and updated Chrome without success. I also attempted with IE11 and received the same error.

**Comment by aesalpas** [comment]
Also, I have verified that the API version is correct.

**Comment by ryanbrainard** [comment]
Have you checked your login history in Salesforce? You might have IP restrictions or something blocking login.

**Comment by aesalpas** [comment]
> Have you checked your login history in Salesforce? You might have IP restrictions or something blocking login.

We do not use login restrictions by IP in Salesforce and, because I am the SF admin, my company has removed IP restrictions on my device. I checked the login record and the connections to Workbench are all marked as "success".

**Comment by thvd** [comment]
With this issue, it's often the case of disabling this checkboxes:

Setup > Session Settings > 
- Lock sessions to the IP address from which they originated
- Lock sessions to the domain in which they were first used

**Comment by aesalpas** [comment]
@thvd Thank you! Disabling the first setting (Lock sessions to the IP address from which they originated) did the trick.

**Comment by rickupton** [comment]
Thank you @thvd and @aesalpas I was having the same problem and unchecking "Lock sessions to the IP address from which they originated" also resolved the problem for me.
