### ISSUE TITLE
Matrix

### ISSUE THREAD

**Issue by ghost** [forceworkbench/forceworkbench#745]
Hi team, 

When I click on Matrix in SOQL Query I no longer have the Column: Row: options (to define which fields should be the column or row.

Without this I cannot seem to get the query to work and display the data in the correct format.

Did you remove this option? Is it possible to still query in the matrix format similar to Salesforce?

I still receive the error "Both column and row must be specified for Matrix view." but there is no option to put this there. 

Thanks
Jake

**Comment by larsenp** [comment]
I have the same issue.

**Comment by dmchaplin** [comment]
same here

**Comment by atnmorrison** [comment]
same here

**Comment by JakeSaul** [comment]
anyone able to help here? 
3 months since I first submitted the issue

**Comment by dgonch5** [comment]
Any updates?

**Comment by schnism** [comment]
Workaround: The fields are still in the page, only hidden by css. If you open the browser developer console, search in the source for "matrix_selection_headers" and remove the style-Attribute for this and the next row, all is working like a charm after that.

If I find some time I will also check why the changing of the radiobuttons does not toggle the visibility anymore....
