### ISSUE TITLE
Workbench working today?

### ISSUE THREAD

**Issue by BenjieAguilar** [forceworkbench/forceworkbench#755]
Is the site offline today?  5/23/2018

**Comment by hroberts6** [comment]
Been getting an Application Error message for the past hour, when clicking the login button.

**Comment by theajaygupta** [comment]
It is working properly for me. 

<img width="1089" alt="screen shot 2018-05-24 at 12 27 23 pm" src="https://user-images.githubusercontent.com/4220500/40461270-df4d8976-5f4d-11e8-894f-9b22b07a469c.png">
