### ISSUE TITLE
UNKNOWN ERROR: SOAP-ERROR: Parsing WSDL: Couldn't load from '/app/workbench/soapclient/sforce.420.partner.wsdl'

### ISSUE THREAD

**Issue by FuentesGames** [forceworkbench/forceworkbench#756]
Im getting the following error after logging in. No functionality is available and the error shows on all screens.

UNKNOWN ERROR: SOAP-ERROR: Parsing WSDL: Couldn't load from '/app/workbench/soapclient/sforce.420.partner.wsdl' : XML declaration allowed only at the start of the document

**Comment by gamacias** [comment]
just to comment  that I was able to log in and use it normally it by changing the Api Version to 41 instead of 42
