### ISSUE TITLE
Error 500 when deploying new version of Workbench

### ISSUE THREAD

**Issue by dmroman** [forceworkbench/forceworkbench#757]
When loading new version of Workbench Server returns error 500 and this appears in server log:

[Wed May 30 11:11:25.264667 2018] [php7:error] [pid 12830] [client 127.0.0.1:59745] PHP Fatal error:  require(): Failed opening required '/Library/Server/Web/Data/Sites/Default/workbench/../vendor/autoload.php' (include_path='.:') in /Library/Server/Web/Data/Sites/Default/workbench/shared.php on line 2

I commented out line 2 on "shared.php" and it started working. Apparently there is a file referenced not included in the package.

**Comment by idanblich** [comment]
+1
