### ISSUE TITLE
403 forbidden issue

### ISSUE THREAD

**Issue by minzsf** [forceworkbench/forceworkbench#758]
**Describe the bug**
Starting from yesterday, I am not able to insert or update data to prod or sandbox from workbench. The 403 error is displayed.

**To Reproduce**
1. Go to workbench
2. Click on data->insert/update
3. select a file
4. click next

**Expected behavior**
display the field mapping

**Screenshots**
![image](https://user-images.githubusercontent.com/40036880/41114687-ff1d9556-6a39-11e8-9f88-1c200ca59ac0.png)

![image](https://user-images.githubusercontent.com/40036880/41114706-0b2fa302-6a3a-11e8-8f3e-1fcc9146251b.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser IE
 - Version 11

**Comment by joshlequire** [comment]
I just experienced the same issue, but with slightly different steps. Here's what I found:

**User / Environment**
- Myself (sys admin with modify all, all permissions)
- Sandbox (staging) environment

**URL where occurred**
https://workbench.developerforce.com/delete.php

**Steps to Reproduce**
1. Authenticate into workbench with a sandbox user
2. Navigate to Data --> Delete
3. Select file for upload (~900k records), click 'next'
4. Receive error

**Expected results**
Proceed to mapping, initiate job. 

**Actual Results**
Receive error: 403 Forbidden. Invalid or missing required CSRF token
