### ISSUE TITLE
Installation Error  

### ISSUE THREAD

**Issue by brainwashed85** [forceworkbench/forceworkbench#764]
**Describe the bug**
I'm using XAMPP for Windows 7.2.6

cloned the full project to my "c:\xampp\htdocs\wb" 
but when i run http://localhost/wb/workbench i get the following error:

```

Warning: require(C:\xampp\htdocs\wb\workbench/../vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\wb\workbench\shared.php on line 2

Fatal error: require(): Failed opening required 'C:\xampp\htdocs\wb\workbench/../vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\wb\workbench\shared.php on line 2


```
**Desktop**
 - OS: windows 10 64bit 
 - Browser: chrome
 - Version 68.0.3440.42
I had the same issue with workbench v42.0
i had to install 41.0.1 to be able to work with the tool again.

**Comment by CarlWeiss** [comment]
See [issue 757](https://github.com/forceworkbench/forceworkbench/issues/757])
Commenting out line #2 in shared.php resolved the issue for me.

**Comment by bpl3792** [comment]
I updated the shared.php to include the actual directory where autoload.php was stored. I am now getting

> 
Warning: Use of undefined constant SOAP_COMPRESSION_ACCEPT - assumed 'SOAP_COMPRESSION_ACCEPT' (this will throw an Error in a future version of PHP) in C:\xampp\htdocs\workbench\soapclient\SforceBaseClient.php on line 110

Warning: Use of undefined constant SOAP_COMPRESSION_GZIP - assumed 'SOAP_COMPRESSION_GZIP' (this will throw an Error in a future version of PHP) in C:\xampp\htdocs\workbench\soapclient\SforceBaseClient.php on line 110

Warning: A non-numeric value encountered in C:\xampp\htdocs\workbench\soapclient\SforceBaseClient.php on line 110

Warning: Use of undefined constant SOAP_COMPRESSION_ACCEPT - assumed 'SOAP_COMPRESSION_ACCEPT' (this will throw an Error in a future version of PHP) in C:\xampp\htdocs\workbench\soapclient\SforceBaseClient.php on line 110

Warning: Use of undefined constant SOAP_COMPRESSION_GZIP - assumed 'SOAP_COMPRESSION_GZIP' (this will throw an Error in a future version of PHP) in C:\xampp\htdocs\workbench\soapclient\SforceBaseClient.php on line 110

Warning: A non-numeric value encountered in C:\xampp\htdocs\workbench\soapclient\SforceBaseClient.php on line 110

Fatal error: Uncaught Error: Class 'SoapClient' not found in C:\xampp\htdocs\workbench\soapclient\SforceBaseClient.php:123 Stack trace: #0 C:\xampp\htdocs\workbench\context\PartnerConnectionProvider.php(9): SforceBaseClient->createConnection('soapclient/sfor...') #1 C:\xampp\htdocs\workbench\context\AbstractConnectionProvider.php(13): PartnerConnectionProvider->establish(Object(ConnectionConfiguration)) #2 C:\xampp\htdocs\workbench\context\CacheableValueProvider.php(18): AbstractConnectionProvider->load(Object(ConnectionConfiguration)) #3 C:\xampp\htdocs\workbench\context\WorkbenchContext.php(231): CacheableValueProvider->get(Object(ConnectionConfiguration)) #4 C:\xampp\htdocs\workbench\context\WorkbenchContext.php(239): WorkbenchContext->getCacheableValue('PARTNER', Object(ConnectionConfiguration)) #5 C:\xampp\htdocs\workbench\context\WorkbenchContext.php(246): WorkbenchContext->getConnection('PARTNER') #6 C:\xampp\htdocs\workbench\context\UserInfoProvider.php(11): WorkbenchContext->getPartnerConnection() #7 C:\xampp\htd in C:\xampp\htdocs\workbench\soapclient\SforceBaseClient.php on line 123
