### ISSUE TITLE
Running on OS X:  Failed opening required '/Library/WebServer/Documents/workbench/../vendor/autoload.php'

### ISSUE THREAD

**Issue by bingwang0** [forceworkbench/forceworkbench#767]
**Describe the bug**
Installation doesn't run with Apache/Php7 included with OS X High Sierra

**To Reproduce**
1. Enable Apache/PHP on OS X.  Also enable SSL (self-signed cert)
2. Verify it works by going to https://localhost/phpinfo.php (simple php info doc)
3. Copy workbench folder into webroot /Library/WebServer/Documents
4. Go to https://localhost/workbench and see this error
_Warning: require(/Library/WebServer/Documents/workbench/../vendor/autoload.php): failed to open stream: No such file or directory in /Library/WebServer/Documents/workbench/shared.php on line 2

Fatal error: require(): Failed opening required '/Library/WebServer/Documents/workbench/../vendor/autoload.php' (include_path='.:') in /Library/WebServer/Documents/workbench/shared.php on line 2_

**Expected behavior**
Loading workbench login page

**Desktop (please complete the following information):**
Chrome current on High Sierra

**Comment by vazexqi** [comment]
I've just merged a PR that lets you run workbench in Docker locally. I think that is the easiest way to get started. It's tested on Mac and Linux 16.04. See https://github.com/forceworkbench/forceworkbench/pull/775

The official mechanism for running workbench is Heroku dynos (this is what we use). We cannot assist with any setup issues that you have on your machine.

**Comment by kgalant** [comment]
So just as a side note, on OS X this bug is (most likely) permissions-related, and will go away by marking the folder as shared (in Finder, right-click, Get Info, mark folder as Shared).
