### ISSUE TITLE
invalid_grant: ip restricted

### ISSUE THREAD

**Issue by etitaev** [forceworkbench/forceworkbench#772]
**Describe the bug**
Cannot login to workbench with my.salesforce.com account.
No problem to login to my.salesforce.com 

The error is:
An error has occurred and you have been logged out:
invalid_grant: ip restricted

Note: we do not use login "login.salesforce.com"

**To Reproduce**
1. login to https://csone.my.salesforce.com/console
2. open https://workbench.developerforce.com/login.php
3. click login with Salesforce

**Expected behavior**
get successful login

**Desktop (please complete the following information):**
 - OS: MAC/ Windows(server/10)
 - Browser [firefox, safari]

**Comment by identigral** [comment]
It's likely that either the profile of the SF user or the org-wide session settings restrict the IP you're logging in from. Please check both of these configuration items:

Org-wide: Security Controls > Session Settings > 'Lock sessions to the IP address from which they originated' should be unchecked
Profile of the user: System > Login IP Ranges. If one or more ranges are listed here, verify that your IP address is on this list.

You can see what Salesforce sees as your IP address by looking at Login History. Login history entries where Login Type = Remote Access 2.0 and Status = Restricted IP correspond to failed oAuth authentication attempts by Workbench on your behalf.

**Comment by shekarr2000** [comment]
Sharing IPs will be helpful. I don't see any document sharing the range of IPs to be whitelisted for workbench. You can't just say look into Login history and add it is misleading as the IPs can be changed and more over we can whitelist only a single IP address by looking at the Login history.
