### ISSUE TITLE
Error while looking for opportunity details when clicking  ID.

### ISSUE THREAD

**Issue by Asmita24** [forceworkbench/forceworkbench#783]
**Describe the bug**

**To Reproduce**
1. Go to '...' SOQL Query
2. Select Oppty and Query any oppty, I queried oppty I owned.
3. click on ID and the next window will give you error:

An existing Opportunity could not found with the id '0063A000015PwKWQA0'. Confirm both the object type and id are correct. 

**Expected behavior**
Should be able to see a tabular view of all values.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
I as system admin can see the Opportunity details , but business admin +modify all+highest role in hierarchy cannot.

**Comment by Bard09** [comment]
I'm getting this error with Firefox, API 44, using an Account ID (that is valid via the SOQL query, but not via the retrieve.php page)
