### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by reynchr** [forceworkbench/forceworkbench#794]
A fatal error occurred. Contact your administrator and provide the following error id:
[future_get-9-1543602652]

when executing the following query

SELECT Id, SObjectType, PermissionsRead, Parent.label, Parent.IsOwnedByProfile
FROM ObjectPermissions
WHERE (ParentId
IN (SELECT PermissionSetId
FROM PermissionSetAssignment
WHERE Assignee.Name = 'Some Name'))
AND
(PermissionRead = true)
AND
(SobjectType = 'Account')

**Comment by rvwatch** [comment]
PermissionRead needs to be PermissionsRead and this should run properly for you. 

SELECT Id, SObjectType, PermissionsRead, Parent.label, Parent.IsOwnedByProfile
FROM ObjectPermissions
WHERE (ParentId
IN (SELECT PermissionSetId
FROM PermissionSetAssignment
WHERE Assignee.Name = 'Some Name'))
AND
(PermissionsRead = true)
AND
(SobjectType = 'Account')

**Comment by vazexqi** [comment]
Closed by #797
