### ISSUE TITLE
A fatal error occurred. Contact your administrator and provide the following error id: [future_get-9-1544023650]

### ISSUE THREAD

**Issue by VinitaKumari163** [forceworkbench/forceworkbench#796]
Hi Team

While doing query getting 'A fatal error occurred. Contact your administrator and provide the following error id:[future_get-9-1544023650]' 
Please suggest how to fix this.

Thanks!
Vinita

**Comment by kdrgitit** [comment]
I have been getting the same error on most of my SOQL queries for the last week.

**Comment by rvwatch** [comment]
Can you copy/paste in the specific query that you're trying to run when you hit this error?

**Comment by rvwatch** [comment]
It appears the error messages are not properly being returned to users. We should have a fix in place soon, but in the meantime just double check your queries for any spelling errors or missing characters.

**Comment by vazexqi** [comment]
Closed by #797
