### ISSUE TITLE
Unable to create local Docker images

### ISSUE THREAD

**Issue by idanblich** [forceworkbench/forceworkbench#801]
**Describe the bug**

Unable to create local docker using latest repo commit
Run ./local.sh

This is the log error:
```
...
heroku-buildpack-php-144/support/installer/src/ComposerInstaller.php
heroku-buildpack-php-144/support/installer/src/ComposerInstallerPlugin.php
heroku-buildpack-php-144/support/installer/src/Downloader.php
Removing intermediate container 19286dfe4edf
 ---> 3a806a54d491
Step 12/13 : RUN /tmp/buildpack/php/bin/compile /app /tmp/build_cache /tmp/env
 ---> Running in 5c047af84d00
-----> Bootstrapping...

 !     ERROR: Failed to download minimal PHP for bootstrapping!
 !
 !     This is most likely a temporary internal error. If the problem
 !     persists, make sure that you are not running a custom or forked
 !     version of the Heroku PHP buildpack which may need updating.

ERROR: Service 'web' failed to build: The command '/bin/sh -c /tmp/buildpack/php/bin/compile /app /tmp/build_cache /tmp/env' returned a non-zero code: 1
```
**To Reproduce**
1. Download zip from repo
2. Unzip
3. Run ./local.sh

**Expected behavior**
Clean installation and a working build of the full app (redis + php ) 

**Desktop (please complete the following information):**
 - OS: macOS Mojava 10.14.2

**Additional context**
When update ENV PHP_BUILDPACK_VERSION v144 --> v149  (On Dokerfile line 3)
Build is working as excepted

**Comment by vazexqi** [comment]
> When update ENV PHP_BUILDPACK_VERSION v144 --> v149 (On Dokerfile line 3)
Build is working as excepted

See #800. Should be merged soon.
