### ISSUE TITLE
Streaming Push Topics constantly handshaking, disconnecting for my org (v44)

### ISSUE THREAD

**Issue by kyleballard** [forceworkbench/forceworkbench#803]
**Describe the bug**
Simply opening the streaming push topics feature on the workbench (https://workbench.developerforce.com/streaming.php) causes an endless stream of handshaking to occur until Salesforce service eventually rejects any new clients from connecting.

**To Reproduce**
1. Go to https://workbench.developerforce.com/select.php
2. Click on Queries > Streaming Push Topics
3. See above described behavior

**Expected behavior**
A single handshake should occur, then it should wait for a connection to a push topic channel.

**Screenshots**

![Error screenshot](http://oi68.tinypic.com/295twlt.jpgg "Error")

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 71
Note:  Also happens in Edge browser.

**Additional context**
This is a standard developer edition org (https://developer.salesforce.com)

**Comment by jsardello** [comment]
Ran into this today with one of our orgs. Very confusing!
