### ISSUE TITLE
Mass Transfer open activities not working

### ISSUE THREAD

**Issue by danieluub** [forceworkbench/forceworkbench#805]
Transfer Open Activities on Owner Change is no longer working on account owner change with open activities.

This was working until recently. I have changed back to API 40, still does not work. 

![image](https://user-images.githubusercontent.com/3029955/52386588-74a54e00-2ad2-11e9-9b3c-a3a55d730121.png)

**Comment by ntotten** [comment]
This product is not supported by Salesforce and as such we cannot provide support on Github. Support requests for Workbench should be opened on [Stackoverflow](https://salesforce.stackexchange.com/questions/tagged/workbench).
