### ISSUE TITLE
User query generates exception

### ISSUE THREAD

**Issue by alpha-bytes** [forceworkbench/forceworkbench#806]
**Describe the bug**
After authenticating Workbench against a client's production org, I ran the following query: 
`select id, profile.name from user`

...which generates the following error message: 
> A fatal error occurred. Contact your administrator and provide the following error id:
[future_get-9-1550070703]

**To Reproduce**
1. Authenticate into Workbench
2. Run query above
3. See if you get the error

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Browser Chrome, current stable channel

**Additional context**
Could be a setting in the client's org, but error message leaves a bit to be desired in terms of troubleshooting.

**Comment by schnism** [comment]
Sorry, for me this query works :)

When running into "Fatal Errors" in Workbench my first next try is to run the same query via Tools -> Execute Anonymous, e.g. as 

```java
system.debug([select id, profile.name from user]);
```
This mostly gives more useful information about the reason of the failure.

**Comment by ntotten** [comment]
This product is not supported by Salesforce and as such we cannot provide support on Github. Support requests for Workbench should be opened on [Stackoverflow](https://salesforce.stackexchange.com/questions/tagged/workbench).
