### ISSUE TITLE
We can not connect to Salesforce from Workbench

### ISSUE THREAD

**Issue by hoaluyenquang** [forceworkbench/forceworkbench#807]
Hi there, 
We are working on Sandbox (Unlimited Edition). We want to check for Rest API so we are trying to use the Workbench (https://workbench.developerforce.com) to connect to our Sandbox but getting the issue "access_denied: end-user denied authorization". Could you tell us the cause of the issue? and how to fix it?

Many thanks,
Hoa Luyen

**Comment by ntotten** [comment]
This product is not supported by Salesforce and as such we cannot provide support on Github. Support requests for Workbench should be opened on [Stackoverflow](https://salesforce.stackexchange.com/questions/tagged/workbench).
