### ISSUE TITLE
Undelete Error: The file uploaded contains more than 50000 records. Please try again.

### ISSUE THREAD

**Issue by StephanoM** [forceworkbench/forceworkbench#808]
Hello,
Im trying to undelete some SF contacts. After exporting the IDs into a CSV using data loader I try to upload the file into the undelete file selection but I keep getting the error message: The file uploaded contains more than 50000 records. Please try again.

My csv file has way less than 50000 records, I even tried with only 10 and I keep getting the same error. 
Any help will be much appriciated.

**Comment by ntotten** [comment]
This product is not supported by Salesforce and as such we cannot provide support on Github. Support requests for Workbench should be opened on [Stackoverflow](https://salesforce.stackexchange.com/questions/tagged/workbench).

For data loading, we suggest one of our supported tools such as [Dataloader.io](dataloader.io).
