### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by chaitanyavellanki** [forceworkbench/forceworkbench#809]
**Describe the bug**
We have a installed package and when we try to fetch the count of data from the iData object we are getting fatal error.

**To Reproduce**
query the data using the below query
SELECT count() FROM skyvvasolutions__IData__c

**Expected behavior**
We should get the count of records.

**Screenshots**
![FatalError](https://user-images.githubusercontent.com/49152115/55323376-39dee700-547f-11e9-9ed9-783ec80ce881.JPG)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : Chrome
 - Version : Version 72.0.3626.121 

**Smartphone (please complete the following information):**
NA

**Additional context**

**Comment by ntotten** [comment]
This product is not supported by Salesforce and as such we cannot provide support on Github. Support requests for Workbench should be opened on [Stackoverflow](https://salesforce.stackexchange.com/questions/tagged/workbench).
