### ISSUE TITLE
Salesforce Workbench error for Sandbox

### ISSUE THREAD

**Issue by gururajb66** [forceworkbench/forceworkbench#811]
Getting the following error on trying to login to Sandbox.

test.salesforce.com’s server IP address could not be found.
Try running Windows Network Diagnostics.
DNS_PROBE_FINISHED_NXDOMAIN

**Comment by goravseth** [comment]
Have not had any issues logging into sandbox lately.  Would consider this to be resolved unless you are still encountering it.
