### ISSUE TITLE
Unable to install properly

### ISSUE THREAD

**Issue by klaypigeon** [forceworkbench/forceworkbench#812]
Spent all day trying to get this working. The docs don't help much at all. Install php, unzip and boom, no problem right. No mention of having to set up or composer or know what it is, debug sodium issues, and the best is it says its compatible with 5.x+ php. You need minimally 5.5 just to support the code (Try:Finally) and end up having to install 7.2.

Has anyone written a real step by step to setting this up (on centos7)? The current whack-a-mole error is simply "cannot connect to host".

**Comment by ntotten** [comment]
This product is not supported by Salesforce and as such we cannot provide support on Github. Support requests for Workbench should be directed to Stackoverflow at https://salesforce.stackexchange.com/questions/tagged/workbench
