### ISSUE TITLE
Task_Trigger: System.LimitException: Apex CPU Time Limit Exceeded

### ISSUE THREAD

**Issue by latikaa** [forceworkbench/forceworkbench#813]
**Describe the bug**
I tried to insert tasks from a csv file using workbench upload to salesforce but receive an error:-
Result: Task_Trigger: System.LimitException: Apex CPU Time Limit Exceeded
Status: CANNOT_UPDATE_INSERT_ACTIVATE_ENTITY

**To Reproduce**
1. Go to '...' Data
2. Click on '....' Insert
3. Scroll down to '....' Task

**Expected behavior**
Normally everyday my team is able to insert tasks using workbench upload

**Screenshots**
![image](https://user-images.githubusercontent.com/50643432/57739839-f8ac3a80-76ac-11e9-8d57-90b612186e16.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome

**Smartphone (please complete the following information):**

**Additional context**
![error](https://user-images.githubusercontent.com/50643432/57739902-39a44f00-76ad-11e9-87b2-4bcbcd2142d4.png)

**Comment by ntotten** [comment]
This project is in maintenance-only mode. No new features will be added and only security bugs will be fixed going forward. For support, we suggest using [Stackoverflow](https://salesforce.stackexchange.com/questions/tagged/workbench). 

The following supported and maintained products are the recommended alternatives to Workbench:
* [Salesforce CLI](https://developer.salesforce.com/tools/sfdxcli)
* [Salesforce Extensions for Visual Studio Code](https://developer.salesforce.com/tools/vscode)
* [DataLoader.io](https://dataloader.io/)
