### ISSUE TITLE
I am trying to insert or update using a file i get 403 error. Please see the attached screenshot fyi. 

### ISSUE THREAD

**Issue by sakethreddy2** [forceworkbench/forceworkbench#814]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sakethreddy2** [comment]
<img width="814" alt="Screen Shot 2019-06-14 at 9 28 00 AM" src="https://user-images.githubusercontent.com/51804270/59523835-2ab8e400-8e87-11e9-81e1-78cc656a5754.png">
When ever i am trying to insert or update a file on an object i am getting the above error

**Comment by ntotten** [comment]
This product is not supported by Salesforce and as such we cannot provide support on Github. Support requests for Workbench should be opened on [Stackoverflow](https://salesforce.stackexchange.com/questions/tagged/workbench).
