### ISSUE TITLE
Continously getting an invalid_grant failure when logging in using custom SF domain

### ISSUE THREAD

**Issue by espressobeanies** [forceworkbench/forceworkbench#815]
**Describe the bug**
When I log into Salesforce Workbench using a custom domain, I continue receiving the following error message: "An error has occurred and you have been logged out.\n invalid grant: authentication_failure"

**To Reproduce**
1. Go to 'https://workbench.developerforce.com/login.php'
2. Click on 'Log in with Salesforce'
3. Scroll down to 'Custom Domain'
4. Enter custom domain credentials and submit
5. See error

**Expected behavior**
The Workbench site itself

**Screenshots**
<img width="955" alt="error" src="https://user-images.githubusercontent.com/22796280/60044672-e00e4780-9690-11e9-9ca4-a38ba969ce7a.png">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox (Incognito mode)
 - Version: 67.04

**Additional context**
N/A

**Comment by jamangini** [comment]
What's your login history within the Salesforce Org tell you, if anything?

**Comment by ntotten** [comment]
This product is not supported by Salesforce and as such we cannot provide support on Github. Support requests for Workbench should be opened on [Stackoverflow](https://salesforce.stackexchange.com/questions/tagged/workbench).
