### ISSUE TITLE
Publish official docker images on docker hub

### ISSUE THREAD

**Issue by timwsuqld** [forceworkbench/forceworkbench#816]
**Is your feature request related to a problem? Please describe.**
Currently users have to build their own docker images for forceworkbench

**Describe the solution you'd like**
Automated builds through dockerhub

**Additional context**
It's very easy to setup Docker hub, link it to the Github repository, and add auto build rules for master, and all tags.

We've setup a fork and put it in dockerhub at https://hub.docker.com/r/suqld/forceworkbench for ourselves.

**Comment by ntotten** [comment]
This project is in maintenance-only mode. No new features will be added and only security bugs will be fixed going forward. For support, we suggest using [Stackoverflow](https://salesforce.stackexchange.com/questions/tagged/workbench). 

The following supported and maintained products are the recommended alternatives to Workbench:
* [Salesforce CLI](https://developer.salesforce.com/tools/sfdxcli)
* [Salesforce Extensions for Visual Studio Code](https://developer.salesforce.com/tools/vscode)
* [DataLoader.io](https://dataloader.io/)
