### ISSUE TITLE
UNKNOWN ERROR: Could not access GitHub tags

### ISSUE THREAD

**Issue by MahmoudMito** [forceworkbench/forceworkbench#817]
I am using workbench 46 and I use the workbench chrome extension to connect and I get this 

UNKNOWN ERROR: Could not access GitHub tags

Initially after setting up work bench I got a message that a  line in file 'shared.php' is causing error it was line 2 calling "autoload.php" I commented it and now I am getting the mentioned error

**Comment by Umpa1** [comment]
I have same error. Did you get your issue solved? How?
Thanks

**Comment by MahmoudMito** [comment]
> I have same error. Did you get your issue solved? How?
> Thanks

Nope, still facing same issue

**Comment by ntotten** [comment]
Unfortunately, we cannot provide support via GitHub issues. Please post your question on the [Trailblazer Community](https://success.salesforce.com), [Stackoverflow](https://salesforce.stackexchange.com/), or through other official support channels.

**Comment by ntotten** [comment]
This product is not supported by Salesforce and as such we cannot provide support on Github. Support requests for Workbench should be directed to Stackoverflow at https://salesforce.stackexchange.com/questions/tagged/workbench
