### ISSUE TITLE
Retrieve data doesn't match changeset

### ISSUE THREAD

**Issue by datapharmer** [forceworkbench/forceworkbench#818]
**Describe the bug**
When running migration -> retrieve against a package name with api 46 the data retrieved matches current org files not, the packaged data.

**To Reproduce**
1. Create a package containing a visualforce component
2. change the contents of the visualforce component
3. retrieve the package via migration -> retrieve and download the zip
4. open the zip and extract the component

**Expected behavior**
Extracted component is expected to match the source from the changeset found by clicking on the changet in the org then scrolling to "change set components" and clicking view source next to the component, but shows the current component including edits made after packaging the changeset.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 75

**Additional context**
May result in the wrong data being retrieved and deployed which could introduce unexpected errors.

**Comment by ntotten** [comment]
This project is in maintenance-only mode. No new features will be added and only security bugs will be fixed going forward. For support, we suggest using [Stackoverflow](https://salesforce.stackexchange.com/questions/tagged/workbench). 

The following supported and maintained products are the recommended alternatives to Workbench:
* [Salesforce CLI](https://developer.salesforce.com/tools/sfdxcli)
* [Salesforce Extensions for Visual Studio Code](https://developer.salesforce.com/tools/vscode)
* [DataLoader.io](https://dataloader.io/)
