### ISSUE TITLE
Login Error: An error has occurred and you have been logged out.

### ISSUE THREAD

**Issue by sqiu-modeln** [forceworkbench/forceworkbench#820]
**Describe the bug**
When I clicked the 'Login with Salesforce' button, there is an error: "An error has occurred and you have been logged out. unknown error: retry your request."

**To Reproduce**
1. I have logged in my salesforce org.
2. Go to 'https://workbench.developerforce.com'
3. Select environment Production, api version 45, click I agree to the terms of service
4. Click on 'Login with Salesforce'
5. See error

**Expected behavior**
I should be able to use workbench as usual.

**Screenshots**
Prepare to login
![Screen Shot 2019-08-08 at 2 20 49 PM](https://user-images.githubusercontent.com/19274027/62728784-a009e680-b9ea-11e9-8a70-327ff95b6f3c.png)

Click the login button and error shows up in the page:
![Screen Shot 2019-08-08 at 2 33 46 PM](https://user-images.githubusercontent.com/19274027/62728818-b2842000-b9ea-11e9-99ed-4896db004ca3.png)

This is my salesforce org login history, seems there is some connection problem from workbench:
![Screen Shot 2019-08-08 at 2 21 23 PM](https://user-images.githubusercontent.com/19274027/62728914-e6f7dc00-b9ea-11e9-85ad-fe0cf7a24c01.png)

I even tried using different browser, but it didn't help.

**Comment by jeremyrussellsmith** [comment]
Having the same issue.

**Comment by JJMorrissey** [comment]
Same issue as well.

**Comment by MaroonSand** [comment]
I'm also having the same problem. My workbench was just working earlier this day. I am on instance CS9

**Comment by mhempen-LFW** [comment]
Same here.

**Comment by ashcommonsense** [comment]
I am also having this issue

**Comment by kingb12** [comment]
Also experiencing this issue

**Comment by bcattaneo** [comment]
Same issue here!

**Comment by Raghavendra-Marthi** [comment]
same issue for me

**Comment by SaiHarshithaBandlamudi** [comment]
Same issue

**Comment by jessewheeler** [comment]
Experiencing this across two separate instances as well

**Comment by snehilkarn12** [comment]
Same issue. Till this gets resolved, can somebody let me know if I have any alternatives?

**Comment by bmckayAG** [comment]
Same issue.  The message seems to talk about v46 even though I've tried 45, 44...

**Comment by HunterBoadwine** [comment]
Same issue.

**Comment by jessewheeler** [comment]
Update on https://help.salesforce.com/home

**Comment by tps-dan** [comment]
![image](https://user-images.githubusercontent.com/53543530/62737025-bb252800-b9e3-11e9-85e0-a2833a28d2fd.png)

https://status.salesforce.com/generalmessages/239

**Comment by ssjsushil** [comment]
Same issue

**Comment by paylors** [comment]
Same here

**Comment by faradayfan** [comment]
Same issue

**Comment by danielmargason** [comment]
Yup, I'm having the same problem.

**Comment by vazexqi** [comment]
Yes, as some of you have posted, it is indeed related to https://status.salesforce.com/generalmessages/239

See https://success.salesforce.com/issues_view?id=a1p3A0000003dkDQAQ for the fix.

Depending on _when_ you last access workbench, you might have been in the small time period when Salesforce was changing the metadata on oAuth refresh tokens, leading them to be invalid.

I was able to reproduce this and what I needed to do (for each org that was affected), was to 

1. Login into the org.
2. Open up the Setup menu and navigate to Apps > Connected Apps > Connected Apps OAuth Usage.
3. Look for Workbench in the list.
4. Click on the number in the User Count column, which will open a new page.
5. On that page, look for the "Revoke All" button and click it.

This will revoke all the refresh tokens with workbench and you should be able to login again.
