### ISSUE TITLE
Invalid client Credentials

### ISSUE THREAD

**Issue by hbwilly54** [forceworkbench/forceworkbench#824]
I am getting the following error when I log in for a sandbox.  :
**An error has occurred and you have been logged out:
invalid_client: invalid client credentials**
I have checked  OAuth and there are two workbench. one is Workbench the Other is Workbench App.

**Comment by Shortciper** [comment]
We are also trying to login to a sandbox and are getting the same exception.  tried relaxing IP range restrictions and installing the Workbench App, but that didn't help either.

**Comment by YTKme** [comment]
I can confirm also, I am getting the same error
```
An error has occurred and you have been logged out:
invalid_client: invalid client credentials
```
Though I can log into Production fine.

**Comment by trighele** [comment]
Yes, I am having this issue. Cannot log into the sandbox. Please help

**Comment by jjurisch** [comment]
Also having same issue in Sandbox after installing the app and setting policies. Production worked fine.

**Comment by robsny** [comment]
Same issue. All permissions [https://help.salesforce.com/articleView?id=connected_app_monitor.htm&type=5](found here are enabled)

**Comment by ntotten** [comment]
We are investigating. Status updates will be posted here: https://workbench.statuspage.io/incidents/l2hcy46d2gvx

**Comment by lathasforce** [comment]
Same issue

**Comment by wyko20** [comment]
same issue here , all permissions are there, follow instructions to the T, still no luck

**Comment by ramjeekabra** [comment]
reinstalling the app in salesforce for OAuth resolved the issue for us.

**Comment by trighele** [comment]
Confirmed this worked for me too. Just uninstalled the Workbench App under "Connected Apps OAUth Usage". Then tried logging back into workbench. It installed it and I was able to access. Good luck all

**Comment by ntotten** [comment]
The issue should be resolved. This should be resolved.

**Comment by bcattaneo** [comment]
> Confirmed this worked for me too. Just uninstalled the Workbench App under "Connected Apps OAUth Usage". Then tried logging back into workbench. It installed it and I was able to access. Good luck all

Just for the record, there's no need to uninstall the app. Just "revoke" the workbench oauth for any or all users (there's a "revoke all" button).

**Comment by hbwilly54** [comment]
it is working
