### ISSUE TITLE
In Query Result, Cell value does not match to column name (View as - List). Also View as - Bulk CSV is giving error.

### ISSUE THREAD

**Issue by manojknit** [forceworkbench/forceworkbench#825]
`**Describe` the bug**
In Query Result, Cell value does not match to column name (View as - List). Also, View as - Bulk CSV is giving an error.

**To Reproduce**
1. Go to SOQL Query
2. Enter query
3. Run Query
4. The result set is not correct. Cell values are not coming under the correct columns. Also CSV is giving error.

**Expected behavior**
Columns should have related values.

**Screenshots**
If applicable, 
![Workbench SOQL Query 2019-08-26 10-39-58(1)](https://user-images.githubusercontent.com/8203276/63710826-f189e200-c7ee-11e9-9d4b-1b559e4b140d.png)
![Workbench SOQL Query 2019-08-26 10-42-57](https://user-images.githubusercontent.com/8203276/63710837-f51d6900-c7ee-11e9-85c8-9b97b196d28c.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MAC
 - Browser [e.g. chrome, safari] Both Chrome and Firefox
 - Version [e.g. 22] Latest

**Comment by ntotten** [comment]
This project is in maintenance-only mode. No new features will be added and only security bugs will be fixed going forward. For support, we suggest using [Stackoverflow](https://salesforce.stackexchange.com/questions/tagged/workbench). 

The following supported and maintained products are the recommended alternatives to Workbench:
* [Salesforce CLI](https://developer.salesforce.com/tools/sfdxcli)
* [Salesforce Extensions for Visual Studio Code](https://developer.salesforce.com/tools/vscode)
* [DataLoader.io](https://dataloader.io/)
