### ISSUE TITLE
Update PHP version

### ISSUE THREAD

**Issue by Feldhacker** [forceworkbench/forceworkbench#828]
When deploying workbench to Heroku, Heroku now gives the warning:

WARNING: Your app's PHP version is close to end of maintenance
Only security updates will be provided for your PHP version series by the PHP Group as of 2019-11-30.
It is strongly recommended you update your app to a version of PHP with "active support" status immediately to ensure you get the latest bugfixes and security updates each time you deploy.

Workbench is currently using PHP 7.2 and needs to be updated to 7.3.

**Comment by ntotten** [comment]
We won't be updating until the security support ends. It is likely Workbench will be discontinued before security support ends in November of 2020. In the unlikely event that Workbench is still maintained after that date, we will update the PHP version.

**Comment by Feldhacker** [comment]
Any suggested replacement for Workbench?
